# Source oh-my-zsh if it is installed.
if [[ -d $HOME/.oh-my-zsh ]]; then
  # Path to your oh-my-zsh configuration.
  ZSH=$HOME/.oh-my-zsh

  # Set name of the theme to load.
  ZSH_THEME="skwp"

  # Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
  # Example format: plugins=(rails git textmate ruby lighthouse)
  plugins=(vi-mode rvm ruby bundler zsh-syntax-highlighting history-substring-search)

  # source every zsh file in user's custom/zsh/before. This is useful for setting theme and plugins.
  if [[ -d ~/.dotfiles/custom/zsh/before ]]; then
    for config_file (~/.dotfiles/custom/zsh/before/*) source $config_file
  fi

  # Figure out if we have Robby's or Sorin's Oh-my-zsh
  if [[ -f $ZSH/oh-my-zsh.sh ]]; then
    source $ZSH/oh-my-zsh.sh # OMZ Robby Russell (https://github.com/robbyrussell/oh-my-zsh)
  else
    source ~/.dotfiles/zsh/omz-sorin/omz-sorin.zsh # OMZ Sorin Ionescu (https://github.com/sorin-ionescu/oh-my-zsh)
  fi
fi

# Configuration
for config_file (~/.dotfiles/zsh/*.zsh) source $config_file

# ------------------
# zsh/after
# ==================
# source every zsh file in user's custom/zsh/after.
if [[ -d ~/.dotfiles/custom/zsh/after ]]; then
  for config_file (~/.dotfiles/custom/zsh/after/*) source $config_file
fi

# Put secret configuration settings in ~/.secrets
if [[ -a ~/.secrets ]] then
  source ~/.secrets
fi

#where all common aliases are
if [[ -a ~/.aliases ]] then
  source  ~/.aliases
fi

if [[ -a  ~/.dotfiles/custom/config ]]; then
  #Additional configuration. I suggest adding PATH in this file
  source ~/.dotfiles/custom/config
fi

if [[ -a ~/.dotfiles/custom/directories ]]; then
  #Aliases for directories
  source ~/.dotfiles/custom/directories
fi
